-- IDs are generated by the application. Timestamps are stored in UTC.

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY,
    email text NOT NULL,
    phone text,
    password_hash text NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('active', 'locked', 'disabled', 'pending')),
    last_login_at timestamptz,
    password_changed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
    ON users (lower(email))
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS platform_roles (
    id uuid PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS platform_permissions (
    id uuid PRIMARY KEY,
    resource text NOT NULL,
    action text NOT NULL,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (resource, action)
);

CREATE TABLE IF NOT EXISTS platform_role_permissions (
    role_id uuid NOT NULL REFERENCES platform_roles(id),
    permission_id uuid NOT NULL REFERENCES platform_permissions(id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS platform_user_roles (
    user_id uuid NOT NULL REFERENCES users(id),
    role_id uuid NOT NULL REFERENCES platform_roles(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS tenants (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'closed')),
    currency char(3) NOT NULL DEFAULT 'USD',
    settings_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tenants_slug_unique
    ON tenants (lower(slug))
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS tenant_members (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    user_id uuid NOT NULL REFERENCES users(id),
    role_code text NOT NULL
        CHECK (role_code IN ('tenant_owner', 'tenant_admin', 'developer', 'viewer')),
    status text NOT NULL DEFAULT 'invited'
        CHECK (status IN ('invited', 'active', 'suspended', 'removed')),
    created_by uuid REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id)
);

CREATE INDEX IF NOT EXISTS tenant_members_user_idx
    ON tenant_members (user_id, status);

CREATE TABLE IF NOT EXISTS projects (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    name text NOT NULL,
    slug text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_by uuid NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS projects_tenant_slug_unique
    ON projects (tenant_id, lower(slug))
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS project_members (
    project_id uuid NOT NULL REFERENCES projects(id),
    user_id uuid NOT NULL REFERENCES users(id),
    role_code text NOT NULL
        CHECK (role_code IN ('project_admin', 'developer', 'viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS web_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    tenant_id uuid REFERENCES tenants(id),
    audience text NOT NULL CHECK (audience IN ('admin', 'console')),
    session_hash text NOT NULL UNIQUE,
    auth_strength text NOT NULL,
    ip_hash text,
    user_agent_hash text,
    expires_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE web_sessions
    ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES tenants(id);

CREATE INDEX IF NOT EXISTS web_sessions_user_idx
    ON web_sessions (user_id, revoked_at, expires_at);

CREATE TABLE IF NOT EXISTS mfa_credentials (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    type text NOT NULL CHECK (type IN ('webauthn', 'totp')),
    label text NOT NULL DEFAULT 'authenticator',
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'active', 'revoked')),
    credential_public_key bytea,
    encrypted_secret bytea,
    last_used_at timestamptz,
    verified_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);

ALTER TABLE mfa_credentials
    ADD COLUMN IF NOT EXISTS label text NOT NULL DEFAULT 'authenticator';

ALTER TABLE mfa_credentials
    ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending';

ALTER TABLE mfa_credentials
    ADD COLUMN IF NOT EXISTS verified_at timestamptz;

ALTER TABLE mfa_credentials
    ADD COLUMN IF NOT EXISTS expires_at timestamptz;

CREATE TABLE IF NOT EXISTS login_throttles (
    subject_hash text PRIMARY KEY,
    failure_count integer NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
    first_failed_at timestamptz NOT NULL,
    locked_until timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    token_hash text NOT NULL UNIQUE,
    requested_ip_hash text,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS password_reset_tokens_user_idx
    ON password_reset_tokens (user_id, used_at, expires_at);

CREATE TABLE IF NOT EXISTS api_tokens (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    project_id uuid NOT NULL REFERENCES projects(id),
    created_by uuid NOT NULL REFERENCES users(id),
    name text NOT NULL,
    token_prefix text NOT NULL,
    token_hash text NOT NULL UNIQUE,
    scopes_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_models_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_ips_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    rate_limit_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    expires_at timestamptz,
    last_used_at timestamptz,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'revoked', 'expired')),
    created_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS api_tokens_scope_idx
    ON api_tokens (tenant_id, project_id, status);

CREATE TABLE IF NOT EXISTS models (
    id uuid PRIMARY KEY,
    provider text NOT NULL,
    model_name text NOT NULL,
    protocol_family text NOT NULL,
    capabilities_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, model_name)
);

CREATE TABLE IF NOT EXISTS channels (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    provider text NOT NULL,
    base_url text NOT NULL,
    credential_ref text NOT NULL,
    status text NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'draining', 'disabled')),
    priority integer NOT NULL DEFAULT 0,
    weight integer NOT NULL DEFAULT 100 CHECK (weight >= 0),
    timeout_policy_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    retry_policy_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    health_status_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS channel_models (
    channel_id uuid NOT NULL REFERENCES channels(id),
    model_id uuid NOT NULL REFERENCES models(id),
    upstream_model_name text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    health_status text NOT NULL DEFAULT 'unknown',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (channel_id, model_id)
);

CREATE TABLE IF NOT EXISTS price_versions (
    id uuid PRIMARY KEY,
    scope_type text NOT NULL
        CHECK (scope_type IN ('platform_default', 'tenant', 'project', 'token')),
    scope_id uuid NOT NULL,
    model_id uuid NOT NULL REFERENCES models(id),
    currency char(3) NOT NULL,
    input_price_per_unit numeric(24, 12) NOT NULL CHECK (input_price_per_unit >= 0),
    output_price_per_unit numeric(24, 12) NOT NULL CHECK (output_price_per_unit >= 0),
    cached_input_price_per_unit numeric(24, 12) NOT NULL DEFAULT 0
        CHECK (cached_input_price_per_unit >= 0),
    reasoning_price_per_unit numeric(24, 12) NOT NULL DEFAULT 0
        CHECK (reasoning_price_per_unit >= 0),
    minimum_charge numeric(24, 12) NOT NULL DEFAULT 0
        CHECK (minimum_charge >= 0),
    version bigint NOT NULL,
    effective_from timestamptz NOT NULL,
    effective_to timestamptz,
    status text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'active', 'retired')),
    created_by uuid NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS price_versions_scope_version_unique
    ON price_versions (scope_type, scope_id, model_id, version);

CREATE TABLE IF NOT EXISTS model_requests (
    id uuid PRIMARY KEY,
    request_id text NOT NULL UNIQUE,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    project_id uuid NOT NULL REFERENCES projects(id),
    token_id uuid NOT NULL REFERENCES api_tokens(id),
    model_id uuid NOT NULL REFERENCES models(id),
    channel_id uuid REFERENCES channels(id),
    status text NOT NULL DEFAULT 'started',
    provider_request_id text,
    input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    cached_input_tokens bigint NOT NULL DEFAULT 0 CHECK (cached_input_tokens >= 0),
    reasoning_tokens bigint NOT NULL DEFAULT 0 CHECK (reasoning_tokens >= 0),
    estimated_amount numeric(24, 12) NOT NULL DEFAULT 0 CHECK (estimated_amount >= 0),
    settled_amount numeric(24, 12) NOT NULL DEFAULT 0 CHECK (settled_amount >= 0),
    currency char(3) NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS model_requests_tenant_created_idx
    ON model_requests (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS usage_events (
    id uuid PRIMARY KEY,
    request_id uuid NOT NULL REFERENCES model_requests(id),
    source text NOT NULL CHECK (source IN ('upstream', 'local_estimate', 'reconciliation')),
    input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    cached_input_tokens bigint NOT NULL DEFAULT 0 CHECK (cached_input_tokens >= 0),
    reasoning_tokens bigint NOT NULL DEFAULT 0 CHECK (reasoning_tokens >= 0),
    raw_usage_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    event_version bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (request_id, source, event_version)
);

CREATE TABLE IF NOT EXISTS billing_reservations (
    id uuid PRIMARY KEY,
    request_id uuid NOT NULL UNIQUE REFERENCES model_requests(id),
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    account_id uuid NOT NULL,
    reserved_amount numeric(24, 12) NOT NULL CHECK (reserved_amount >= 0),
    settled_amount numeric(24, 12) NOT NULL DEFAULT 0 CHECK (settled_amount >= 0),
    released_amount numeric(24, 12) NOT NULL DEFAULT 0 CHECK (released_amount >= 0),
    currency char(3) NOT NULL,
    status text NOT NULL DEFAULT 'held'
        CHECK (status IN ('held', 'settled', 'released', 'expired')),
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_accounts (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES tenants(id),
    account_type text NOT NULL
        CHECK (account_type IN ('prepaid_balance', 'credit', 'receivable')),
    currency char(3) NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, account_type, currency)
);

CREATE TABLE IF NOT EXISTS ledger_transactions (
    id uuid PRIMARY KEY,
    idempotency_key text NOT NULL UNIQUE,
    transaction_type text NOT NULL,
    reference_type text NOT NULL,
    reference_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_lines (
    id uuid PRIMARY KEY,
    transaction_id uuid NOT NULL REFERENCES ledger_transactions(id),
    account_id uuid NOT NULL REFERENCES ledger_accounts(id),
    direction text NOT NULL CHECK (direction IN ('debit', 'credit')),
    amount numeric(24, 12) NOT NULL CHECK (amount > 0),
    currency char(3) NOT NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ledger_lines_account_created_idx
    ON ledger_lines (account_id, created_at);

CREATE TABLE IF NOT EXISTS audit_events (
    id uuid PRIMARY KEY,
    request_id text NOT NULL,
    actor_type text NOT NULL,
    actor_id uuid,
    tenant_id uuid REFERENCES tenants(id),
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id uuid,
    result text NOT NULL CHECK (result IN ('success', 'denied', 'failed')),
    before_json jsonb,
    after_json jsonb,
    ip_hash text,
    user_agent_hash text,
    reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_tenant_created_idx
    ON audit_events (tenant_id, created_at);

CREATE TABLE IF NOT EXISTS outbox_events (
    id uuid PRIMARY KEY,
    event_type text NOT NULL,
    aggregate_type text NOT NULL,
    aggregate_id uuid NOT NULL,
    payload_json jsonb NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'published', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);

CREATE INDEX IF NOT EXISTS outbox_pending_idx
    ON outbox_events (status, next_attempt_at, created_at);
