import { Bell, Check, Clock3, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Language, Announcement, LoginMessage } from "@/types";
import { MarkdownContent } from "@/components/MarkdownContent";

export function ConsoleAnnouncementsPanel({ language, announcements, busy, message, markRead, refresh }: { language: Language; announcements: Announcement[]; busy: boolean; message: LoginMessage; markRead: (announcement: Announcement) => Promise<void>; refresh: () => Promise<void> }) {
  const unread = announcements.filter((item) => !item.read_at).length;
  return <div className="space-y-5">
    <section className="border border-indigo-500/20 bg-indigo-500/[0.045] px-5 py-6 shadow-sm dark:border-indigo-400/20 sm:px-7">
      <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-indigo-700 dark:text-indigo-300"><Bell className="h-4 w-4" />{language === "zh" ? "平台公告" : "Platform announcements"}</div>
      <div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-slate-950 dark:text-white">{language === "zh" ? "公告中心" : "Announcement center"}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{language === "zh" ? "查看平台最新通知、服务变更和维护安排。" : "Review platform updates, service changes, and maintenance notices."}</p></div><div className="flex items-center gap-2"><Badge variant={unread > 0 ? "destructive" : "success"}>{unread} {language === "zh" ? "条未读" : "unread"}</Badge><Button type="button" variant="outline" size="icon" onClick={() => void refresh()} disabled={busy} title={language === "zh" ? "刷新公告" : "Refresh announcements"} aria-label={language === "zh" ? "刷新公告" : "Refresh announcements"}><RefreshCw className={busy ? "h-4 w-4 animate-spin" : "h-4 w-4"} /></Button></div></div>
    </section>
    {message.text ? <div className={message.kind === "error" ? "rounded-xl border border-rose-500/30 bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-500/10 dark:text-rose-300" : "rounded-xl border border-emerald-500/30 bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300"}>{message.text}</div> : null}
    {busy && announcements.length === 0 ? <Card><CardContent className="flex min-h-40 items-center justify-center gap-2 text-sm text-slate-500"><RefreshCw className="h-4 w-4 animate-spin" />{language === "zh" ? "正在加载公告..." : "Loading announcements..."}</CardContent></Card> : announcements.length === 0 ? <Card><CardContent className="py-16 text-center text-sm text-slate-500 dark:text-slate-400">{language === "zh" ? "当前没有生效中的公告。" : "There are no active announcements."}</CardContent></Card> : announcements.map((item) => <Card key={item.id} className={!item.read_at ? "border-indigo-500/30 shadow-md shadow-indigo-500/5" : "border-slate-200/80 dark:border-slate-800"}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-lg">{!item.read_at ? <span className="h-2 w-2 rounded-full bg-rose-500" /> : null}{item.title}</CardTitle><CardDescription className="mt-2 flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{new Date(item.effective_at).toLocaleString(language === "zh" ? "zh-CN" : "en-US")}</CardDescription></div>{!item.read_at ? <Badge variant="warning">{language === "zh" ? "未读" : "Unread"}</Badge> : <Badge variant="muted"><Check className="h-3 w-3" />{language === "zh" ? "已读" : "Read"}</Badge>}</div></CardHeader><CardContent><MarkdownContent content={item.content} className="text-sm text-slate-700 dark:text-slate-300" />{!item.read_at ? <div className="mt-4 flex justify-end"><Button type="button" size="sm" onClick={() => void markRead(item)} className="gap-2"><Check className="h-4 w-4" />{language === "zh" ? "标记已读" : "Mark as read"}</Button></div> : null}</CardContent></Card>)}
  </div>;
}
